name = "svault-bot"
main = "src/index.js"
compatibility_date = "2026-09-17"

routes = [
  { pattern = "toelicking.selenevault.bot.jzadl.xyz", custom_domain = true }
]

[vars]
CDN_BASE = "https://raw.githubusercontent.com/jzadl/selenevault/main"
SITE_URL = "https://svault.jzadl.xyz"
GITHUB_API_BASE = "https://api.github.com/repos/jzadl/selenevault"

# Set with: wrangler secret put TELEGRAM_BOT_TOKEN
