name: Manual Notify Send

on:
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Send to Telegram
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: |
          IFS=',' read -ra IDS <<< "$CHAT_IDS"
          for ID in "${IDS[@]}"; do
            ID_TRIMMED=$(echo "$ID" | xargs)
            curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
              -d "chat_id=${ID_TRIMMED}" \
              -d "parse_mode=MarkdownV2" \
              --data-urlencode "text=*OrangeFox Recovery Project* by sabrinium0 was added to \`recovery.sman\` and its live on svault.jzadl.xyz!"
            echo ""
          done

      - name: Close issue 47
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue close 47 --repo "${{ github.repository }}"
